services:
  app:
    container_name: node-bot-dev
    image: elsantiagod/bot-app-dev:latest
    restart: unless-stopped
    volumes:
      - ./auth_info_dev:/app/auth_info_dev
      - ./bot_memory_dev.db:/app/bot_memory_dev.db
    environment:
      AUTH_FOLDER_PATH: /app/auth_info_dev
      DB_PATH: /app/bot_memory_dev.db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      GOOGLE_SHEETS_ID: ${GOOGLE_SHEETS_ID}
      SHEETS_VENTAS_NOMBRE: ${SHEETS_VENTAS_NOMBRE}
      GRUPO_AUTORIZADO: ${GRUPO_AUTORIZADO_DEV}
      LOG_LEVEL: ${LOG_LEVEL}
