import { normalizarTexto } from './helpers';

/**
 * Diccionario de municipios colombianos → nombre del departamento.
 *
 * Claves: nombre del municipio en MAYÚSCULAS SIN TILDES (forma normalizada).
 * Valores: nombre del departamento con tildes para visualización.
 *
 * ~1120 municipios de los 32 departamentos + Bogotá D.C.
 *
 * Nota sobre duplicados: cuando dos municipios comparten nombre en distintos
 * departamentos, se eligió el más poblado o capital departamental.
 * Los municipios con nombre ambiguo se documentan con comentarios.
 *
 * Uso:
 *   obtenerDepartamento("Armenia")  → "QUINDÍO"
 *   obtenerDepartamento("bogotá")   → "CUNDINAMARCA"
 *   obtenerDepartamento("XYZ")      → "N/A"
 */
const MUNICIPIOS_COLOMBIA: Record<string, string> = {

    // ─── AMAZONAS (11) ────────────────────────────────────────────────────────
    "LETICIA": "AMAZONAS",
    "EL ENCANTO": "AMAZONAS",
    "LA CHORRERA": "AMAZONAS",
    "LA PEDRERA": "AMAZONAS",
    "MIRITI-PARANA": "AMAZONAS",
    "PUERTO ALEGRIA": "AMAZONAS",
    "PUERTO ARICA": "AMAZONAS",
    "PUERTO NARINO": "AMAZONAS",
    "TARAPACA": "AMAZONAS",

    // ─── ANTIOQUIA (125) ──────────────────────────────────────────────────────
    "MEDELLIN": "ANTIOQUIA",
    "ABEJORRAL": "ANTIOQUIA",
    "ABRIAQUI": "ANTIOQUIA",
    "ALEJANDRIA": "ANTIOQUIA",
    "AMAGA": "ANTIOQUIA",
    "AMALFI": "ANTIOQUIA",
    "ANDES": "ANTIOQUIA",
    "ANGELOPOLIS": "ANTIOQUIA",
    "ANGOSTURA": "ANTIOQUIA",
    "ANORI": "ANTIOQUIA",
    "SANTA FE DE ANTIOQUIA": "ANTIOQUIA",
    "ANZA": "ANTIOQUIA",
    "APARTADO": "ANTIOQUIA",
    "ARBOLETES": "ANTIOQUIA",
    "BARBOSA": "ANTIOQUIA",
    "BELLO": "ANTIOQUIA",
    "BELMIRA": "ANTIOQUIA",
    "BETANIA": "ANTIOQUIA",
    "BETULIA": "ANTIOQUIA",
    "CIUDAD BOLIVAR": "ANTIOQUIA",
    "BURITICA": "ANTIOQUIA",
    "CACERES": "ANTIOQUIA",
    "CAICEDO": "ANTIOQUIA",
    "CAMPAMENTO": "ANTIOQUIA",
    "CANASGORDAS": "ANTIOQUIA",
    "CARACOLI": "ANTIOQUIA",
    "CARAMANTA": "ANTIOQUIA",
    "CAREPA": "ANTIOQUIA",
    "EL CARMEN DE VIBORAL": "ANTIOQUIA",
    "CAROLINA DEL PRINCIPE": "ANTIOQUIA",
    "CAUCASIA": "ANTIOQUIA",
    "CHIGORODO": "ANTIOQUIA",
    "CISNEROS": "ANTIOQUIA",
    "COCORNA": "ANTIOQUIA",
    "CONCORDIA": "ANTIOQUIA",
    "COPACABANA": "ANTIOQUIA",
    "DABEIBA": "ANTIOQUIA",
    "DONMATIAS": "ANTIOQUIA",
    "EBEJICO": "ANTIOQUIA",
    "EL BAGRE": "ANTIOQUIA",
    "ENTRERRIOS": "ANTIOQUIA",
    "ENVIGADO": "ANTIOQUIA",
    "FREDONIA": "ANTIOQUIA",
    "FRONTINO": "ANTIOQUIA",
    "GIRALDO": "ANTIOQUIA",
    "GIRARDOTA": "ANTIOQUIA",
    "GOMEZ PLATA": "ANTIOQUIA",
    "GUARNE": "ANTIOQUIA",
    "GUATAPE": "ANTIOQUIA",
    "HELICONIA": "ANTIOQUIA",
    "HISPANIA": "ANTIOQUIA",
    "ITAGUI": "ANTIOQUIA",
    "ITUANGO": "ANTIOQUIA",
    "JARDIN": "ANTIOQUIA",
    "LA CEJA": "ANTIOQUIA",
    "LA ESTRELLA": "ANTIOQUIA",
    "LA PINTADA": "ANTIOQUIA",
    "LIBORINA": "ANTIOQUIA",
    "MACEO": "ANTIOQUIA",
    "MARINILLA": "ANTIOQUIA",
    "MONTEBELLO": "ANTIOQUIA",
    "MURINDO": "ANTIOQUIA",
    "MUTATA": "ANTIOQUIA",
    "NECOCLI": "ANTIOQUIA",
    "NECHI": "ANTIOQUIA",
    "OLAYA": "ANTIOQUIA",
    "PENOL": "ANTIOQUIA",
    "PEQUE": "ANTIOQUIA",
    "PUEBLORRICO": "ANTIOQUIA",
    "PUERTO BERRIO": "ANTIOQUIA",
    "PUERTO NARE": "ANTIOQUIA",
    "PUERTO TRIUNFO": "ANTIOQUIA",
    "REMEDIOS": "ANTIOQUIA",
    "RETIRO": "ANTIOQUIA",
    "RIONEGRO": "ANTIOQUIA",
    "SABANETA": "ANTIOQUIA",
    "SALGAR": "ANTIOQUIA",
    "SAN ANDRES DE CUERQUIA": "ANTIOQUIA",
    "SAN CARLOS": "ANTIOQUIA",
    "SAN FRANCISCO": "ANTIOQUIA",
    "SAN JERONIMO": "ANTIOQUIA",
    "SAN JOSE DE LA MONTANA": "ANTIOQUIA",
    "SAN JUAN DE URABA": "ANTIOQUIA",
    "SAN LUIS": "ANTIOQUIA",
    "SAN PEDRO": "ANTIOQUIA",
    "SAN PEDRO DE URABA": "ANTIOQUIA",
    "SAN RAFAEL": "ANTIOQUIA",
    "SAN ROQUE": "ANTIOQUIA",
    "SAN VICENTE": "ANTIOQUIA",
    "SANTA BARBARA": "ANTIOQUIA",
    "SANTA ROSA DE OSOS": "ANTIOQUIA",
    "SANTO DOMINGO": "ANTIOQUIA",
    "EL SANTUARIO": "ANTIOQUIA",
    "SEGOVIA": "ANTIOQUIA",
    "SONSON": "ANTIOQUIA",
    "SOPETRAN": "ANTIOQUIA",
    "TAMESIS": "ANTIOQUIA",
    "TARAZA": "ANTIOQUIA",
    "TARSO": "ANTIOQUIA",
    "TITIRIBI": "ANTIOQUIA",
    "TURBO": "ANTIOQUIA",
    "URAMITA": "ANTIOQUIA",
    "URRAO": "ANTIOQUIA",
    "VEGACHI": "ANTIOQUIA",
    "VIGIA DEL FUERTE": "ANTIOQUIA",
    "YALI": "ANTIOQUIA",
    "YARUMAL": "ANTIOQUIA",
    "YOLOMBO": "ANTIOQUIA",
    "YONDO": "ANTIOQUIA",
    "ZARAGOZA": "ANTIOQUIA",

    // ─── ARAUCA (7) ───────────────────────────────────────────────────────────
    "ARAUCA": "ARAUCA",
    "ARAUQUITA": "ARAUCA",
    "CRAVO NORTE": "ARAUCA",
    "FORTUL": "ARAUCA",
    "PUERTO RONDON": "ARAUCA",
    "SARAVENA": "ARAUCA",
    "TAME": "ARAUCA",

    // ─── ATLÁNTICO (23) ───────────────────────────────────────────────────────
    "BARRANQUILLA": "ATLÁNTICO",
    "BARANOA": "ATLÁNTICO",
    "CAMPO DE LA CRUZ": "ATLÁNTICO",
    "CANDELARIA": "ATLÁNTICO",
    "GALAPA": "ATLÁNTICO",
    "JUAN DE ACOSTA": "ATLÁNTICO",
    "LURUACO": "ATLÁNTICO",
    "MALAMBO": "ATLÁNTICO",
    "MANATI": "ATLÁNTICO",
    "PALMAR DE VARELA": "ATLÁNTICO",
    "PIOJO": "ATLÁNTICO",
    "POLONUEVO": "ATLÁNTICO",
    "PONEDERA": "ATLÁNTICO",
    "PUERTO COLOMBIA": "ATLÁNTICO",
    "REPELON": "ATLÁNTICO",
    "SABANAGRANDE": "ATLÁNTICO",
    "SABANALARGA": "ATLÁNTICO",
    "SANTA LUCIA": "ATLÁNTICO",
    "SANTO TOMAS": "ATLÁNTICO",
    "SOLEDAD": "ATLÁNTICO",
    "SUAN": "ATLÁNTICO",
    "TUBARA": "ATLÁNTICO",
    "USIACURI": "ATLÁNTICO",

    // ─── BOLÍVAR (46) ─────────────────────────────────────────────────────────
    "CARTAGENA": "BOLÍVAR",
    "CARTAGENA DE INDIAS": "BOLÍVAR",
    "ACHI": "BOLÍVAR",
    "ALTOS DEL ROSARIO": "BOLÍVAR",
    "ARENAL": "BOLÍVAR",
    "ARJONA": "BOLÍVAR",
    "ARROYOHONDO": "BOLÍVAR",
    "BARRANCO DE LOBA": "BOLÍVAR",
    "CALAMAR": "BOLÍVAR",
    "CANTAGALLO": "BOLÍVAR",
    "CICUCO": "BOLÍVAR",
    "EL CARMEN DE BOLIVAR": "BOLÍVAR",
    "EL GUAMO": "BOLÍVAR",
    "EL PENON": "BOLÍVAR",
    "HATILLO DE LOBA": "BOLÍVAR",
    "MAGANGUE": "BOLÍVAR",
    "MAHATES": "BOLÍVAR",
    "MARGARITA": "BOLÍVAR",
    "MARIA LA BAJA": "BOLÍVAR",
    "MOMPOS": "BOLÍVAR",
    "MORALES": "BOLÍVAR",
    "NOROSI": "BOLÍVAR",
    "PINILLOS": "BOLÍVAR",
    "REGIDOR": "BOLÍVAR",
    "RIO VIEJO": "BOLÍVAR",
    "SAN CRISTOBAL": "BOLÍVAR",
    "SAN ESTANISLAO": "BOLÍVAR",
    "SAN FERNANDO": "BOLÍVAR",
    "SAN JACINTO": "BOLÍVAR",
    "SAN JACINTO DEL CAUCA": "BOLÍVAR",
    "SAN JUAN NEPOMUCENO": "BOLÍVAR",
    "SAN MARTIN DE LOBA": "BOLÍVAR",
    "SAN PABLO": "BOLÍVAR",
    "SANTA CATALINA": "BOLÍVAR",
    "SANTA ROSA": "BOLÍVAR",
    "SANTA ROSA DEL SUR": "BOLÍVAR",
    "SIMITI": "BOLÍVAR",
    "SOPLAVIENTO": "BOLÍVAR",
    "TALAIGUA NUEVO": "BOLÍVAR",
    "TIQUISIO": "BOLÍVAR",
    "TURBACO": "BOLÍVAR",
    "TURBANA": "BOLÍVAR",
    "ZAMBRANO": "BOLÍVAR",

    // ─── BOYACÁ (123) ─────────────────────────────────────────────────────────
    "TUNJA": "BOYACÁ",
    "ALMEIDA": "BOYACÁ",
    "AQUITANIA": "BOYACÁ",
    "ARCABUCO": "BOYACÁ",
    "BELEN": "BOYACÁ",
    "BERBEO": "BOYACÁ",
    "BETEITIVA": "BOYACÁ",
    "BOAVITA": "BOYACÁ",
    "BOYACA": "BOYACÁ",
    "BRICENO": "BOYACÁ",
    "BUENAVISTA": "BOYACÁ",
    "BUSBANZA": "BOYACÁ",
    "CAMPOHERMOSO": "BOYACÁ",
    "CERINZA": "BOYACÁ",
    "CHINAVITA": "BOYACÁ",
    "CHIQUINQUIRA": "BOYACÁ",
    "CHIQUIZA": "BOYACÁ",
    "CHISCAS": "BOYACÁ",
    "CHITA": "BOYACÁ",
    "CHITARAQUE": "BOYACÁ",
    "CHIVATA": "BOYACÁ",
    "CIENEGA": "BOYACÁ",
    "COMBITA": "BOYACÁ",
    "COPER": "BOYACÁ",
    "CORRALES": "BOYACÁ",
    "COVARACHIA": "BOYACÁ",
    "CUBARA": "BOYACÁ",
    "CUCAITA": "BOYACÁ",
    "CUITIVA": "BOYACÁ",
    "DUITAMA": "BOYACÁ",
    "EL COCUY": "BOYACÁ",
    "EL ESPINO": "BOYACÁ",
    "FIRAVITOBA": "BOYACÁ",
    "FLORESTA": "BOYACÁ",
    "GACHANTIVA": "BOYACÁ",
    "GAMEZA": "BOYACÁ",
    "GARAGOA": "BOYACÁ",
    "GUACAMAYAS": "BOYACÁ",
    "GUATEQUE": "BOYACÁ",
    "GUAYATA": "BOYACÁ",
    "GUICAN": "BOYACÁ",
    "IZA": "BOYACÁ",
    "JENESANO": "BOYACÁ",
    "JERICO": "BOYACÁ",
    "LA CAPILLA": "BOYACÁ",
    "LA UVITA": "BOYACÁ",
    "LABRANZAGRANDE": "BOYACÁ",
    "MACANAL": "BOYACÁ",
    "MARAPI": "BOYACÁ",
    "MIRAFLORES": "BOYACÁ",
    "MONGUA": "BOYACÁ",
    "MONGUI": "BOYACÁ",
    "MONIQUIRA": "BOYACÁ",
    "MOTAVITA": "BOYACÁ",
    "MUZO": "BOYACÁ",
    "NOBSA": "BOYACÁ",
    "NUEVO COLON": "BOYACÁ",
    "OICATA": "BOYACÁ",
    "OTANCHE": "BOYACÁ",
    "PACHAVITA": "BOYACÁ",
    "PAIPA": "BOYACÁ",
    "PAJARITO": "BOYACÁ",
    "PANQUEBA": "BOYACÁ",
    "PAUNA": "BOYACÁ",
    "PAYA": "BOYACÁ",
    "PAZ DE RIO": "BOYACÁ",
    "PESCA": "BOYACÁ",
    "PISBA": "BOYACÁ",
    "PUERTO BOYACA": "BOYACÁ",
    "QUIPAMA": "BOYACÁ",
    "RAMIRIQUI": "BOYACÁ",
    "RAQUIRA": "BOYACÁ",
    "RONDON": "BOYACÁ",
    "SABOYA": "BOYACÁ",
    "SACHICA": "BOYACÁ",
    "SAMACA": "BOYACÁ",
    "SAN EDUARDO": "BOYACÁ",
    "SAN JOSE DE PARE": "BOYACÁ",
    "SAN LUIS DE GACENO": "BOYACÁ",
    "SAN MATEO": "BOYACÁ",
    "SAN MIGUEL DE SEMA": "BOYACÁ",
    "SAN PABLO DE BORBUR": "BOYACÁ",
    "SANTA MARIA": "BOYACÁ",
    "SANTA ROSA DE VITERBO": "BOYACÁ",
    "SANTA SOFIA": "BOYACÁ",
    "SANTANA": "BOYACÁ",
    "SATIVANORTE": "BOYACÁ",
    "SATIVASUR": "BOYACÁ",
    "SIACHOQUE": "BOYACÁ",
    "SOATA": "BOYACÁ",
    "SOCOTA": "BOYACÁ",
    "SOCHA": "BOYACÁ",
    "SOGAMOSO": "BOYACÁ",
    "SOMONDOCO": "BOYACÁ",
    "SORA": "BOYACÁ",
    "SORACA": "BOYACÁ",
    "SOTAQUIRA": "BOYACÁ",
    "SUSACON": "BOYACÁ",
    "SUTAMARCHAN": "BOYACÁ",
    "SUTATENZA": "BOYACÁ",
    "TASCO": "BOYACÁ",
    "TENZA": "BOYACÁ",
    "TIBANA": "BOYACÁ",
    "TIBASOSA": "BOYACÁ",
    "TINJACA": "BOYACÁ",
    "TIPACOQUE": "BOYACÁ",
    "TOCA": "BOYACÁ",
    "TOGUI": "BOYACÁ",
    "TOTA": "BOYACÁ",
    "TUNUNAGUA": "BOYACÁ",
    "TURMEQUE": "BOYACÁ",
    "TUTA": "BOYACÁ",
    "TUTAZA": "BOYACÁ",
    "UMBITA": "BOYACÁ",
    "VENTAQUEMADA": "BOYACÁ",
    "VILLA DE LEYVA": "BOYACÁ",
    "VIRACACHA": "BOYACÁ",
    "ZETAQUIRA": "BOYACÁ",

    // ─── CALDAS (27) ──────────────────────────────────────────────────────────
    "MANIZALES": "CALDAS",
    "AGUADAS": "CALDAS",
    "ANSERMA": "CALDAS",
    "ARANZAZU": "CALDAS",
    "BELALCAZAR": "CALDAS",
    "CHINCHINA": "CALDAS",
    "FILADELFIA": "CALDAS",
    "LA DORADA": "CALDAS",
    "LA MERCED": "CALDAS",
    "MANZANARES": "CALDAS",
    "MARMATO": "CALDAS",
    "MARQUETALIA": "CALDAS",
    "MARULANDA": "CALDAS",
    "NEIRA": "CALDAS",
    "NORCASIA": "CALDAS",
    "PACORA": "CALDAS",
    "PALESTINA": "CALDAS",
    "PENSILVANIA": "CALDAS",
    "RIOSUCIO": "CALDAS",       // Riosucio Caldas (carnaval)
    "RISARALDA": "CALDAS",      // municipio Risaralda, dep Caldas
    "SALAMINA": "CALDAS",       // Salamina Caldas
    "SAMANA": "CALDAS",
    "SUPIA": "CALDAS",
    "VICTORIA": "CALDAS",
    "VILLAMARIA": "CALDAS",
    "VITERBO": "CALDAS",

    // ─── CAQUETÁ (16) ─────────────────────────────────────────────────────────
    "FLORENCIA": "CAQUETÁ",
    "ALBANIA": "CAQUETÁ",
    "BELEN DE LOS ANDAQUIES": "CAQUETÁ",
    "CARTAGENA DEL CHAIRA": "CAQUETÁ",
    "CURILLO": "CAQUETÁ",
    "EL DONCELLO": "CAQUETÁ",
    "EL PAUJIL": "CAQUETÁ",
    "LA MONTANITA": "CAQUETÁ",
    "MILAN": "CAQUETÁ",
    "MORELIA": "CAQUETÁ",
    "PUERTO RICO": "CAQUETÁ",
    "SAN JOSE DEL FRAGUA": "CAQUETÁ",
    "SAN VICENTE DEL CAGUAN": "CAQUETÁ",
    "SOLANO": "CAQUETÁ",
    "SOLITA": "CAQUETÁ",
    "VALPARAISO": "CAQUETÁ",

    // ─── CASANARE (19) ────────────────────────────────────────────────────────
    "YOPAL": "CASANARE",
    "AGUAZUL": "CASANARE",
    "CHAMEZA": "CASANARE",
    "HATO COROZAL": "CASANARE",
    "LA SALINA": "CASANARE",
    "MANI": "CASANARE",
    "MONTERREY": "CASANARE",
    "NUNCHIA": "CASANARE",
    "OROCUE": "CASANARE",
    "PAZ DE ARIPORO": "CASANARE",
    "PORE": "CASANARE",
    "RECETOR": "CASANARE",
    "SACAMA": "CASANARE",
    "SAN LUIS DE PALENQUE": "CASANARE",
    "TAMARA": "CASANARE",
    "TAURAMENA": "CASANARE",
    "TRINIDAD": "CASANARE",
    "VILLANUEVA": "CASANARE",

    // ─── CAUCA (42) ───────────────────────────────────────────────────────────
    "POPAYAN": "CAUCA",
    "ALMAGUER": "CAUCA",
    "ARGELIA": "CAUCA",
    "BALBOA": "CAUCA",
    "BUENOS AIRES": "CAUCA",
    "CAJIBIO": "CAUCA",
    "CALDONO": "CAUCA",
    "CALOTO": "CAUCA",
    "CORINTO": "CAUCA",
    "EL TAMBO": "CAUCA",
    "GUACHENE": "CAUCA",
    "GUAPI": "CAUCA",
    "INZA": "CAUCA",
    "JAMBALO": "CAUCA",
    "LA SIERRA": "CAUCA",
    "LA VEGA": "CAUCA",
    "LOPEZ DE MICAY": "CAUCA",
    "MERCADERES": "CAUCA",
    "MIRANDA": "CAUCA",
    "PADILLA": "CAUCA",
    "PATIA": "CAUCA",
    "PIAMONTE": "CAUCA",
    "PIENDAMO": "CAUCA",
    "PUERTO TEJADA": "CAUCA",
    "PURACE": "CAUCA",
    "ROSAS": "CAUCA",
    "SAN SEBASTIAN": "CAUCA",
    "SANTANDER DE QUILICHAO": "CAUCA",
    "SILVIA": "CAUCA",
    "SOTARA": "CAUCA",
    "SUAREZ": "CAUCA",
    "TIMBIO": "CAUCA",
    "TIMBIQUI": "CAUCA",
    "TORIBIO": "CAUCA",
    "TOTORO": "CAUCA",
    "VILLA RICA": "CAUCA",

    // ─── CESAR (25) ───────────────────────────────────────────────────────────
    "VALLEDUPAR": "CESAR",
    "AGUACHICA": "CESAR",
    "AGUSTIN CODAZZI": "CESAR",
    "ASTREA": "CESAR",
    "BECERRIL": "CESAR",
    "BOSCONIA": "CESAR",
    "CHIMICHAGUA": "CESAR",
    "CHIRIGUANA": "CESAR",
    "CURUMANI": "CESAR",
    "EL COPEY": "CESAR",
    "EL PASO": "CESAR",
    "GAMARRA": "CESAR",
    "GONZALEZ": "CESAR",
    "LA GLORIA": "CESAR",
    "LA JAGUA DE IBIRICO": "CESAR",
    "LA PAZ": "CESAR",
    "MANAURE BALCON DEL CESAR": "CESAR",
    "PAILITAS": "CESAR",
    "PELAYA": "CESAR",
    "PUEBLO BELLO": "CESAR",
    "RIO DE ORO": "CESAR",
    "LA JAGUA DEL PILAR": "CESAR",
    "SAN ALBERTO": "CESAR",
    "SAN DIEGO": "CESAR",
    "TAMALAMEQUE": "CESAR",

    // ─── CHOCÓ (30) ───────────────────────────────────────────────────────────
    "QUIBDO": "CHOCÓ",
    "ACANDI": "CHOCÓ",
    "ALTO BAUDO": "CHOCÓ",
    "ATRATO": "CHOCÓ",
    "BAGADO": "CHOCÓ",
    "BAHIA SOLANO": "CHOCÓ",
    "BAJO BAUDO": "CHOCÓ",
    "BOJAYA": "CHOCÓ",
    "CARMEN DEL DARIEN": "CHOCÓ",
    "CERTEGUI": "CHOCÓ",
    "CONDOTO": "CHOCÓ",
    "EL CANTON DEL SAN PABLO": "CHOCÓ",
    "EL CARMEN DE ATRATO": "CHOCÓ",
    "EL LITORAL DEL SAN JUAN": "CHOCÓ",
    "ISTMINA": "CHOCÓ",
    "JURADO": "CHOCÓ",
    "LLORO": "CHOCÓ",
    "MEDIO ATRATO": "CHOCÓ",
    "MEDIO BAUDO": "CHOCÓ",
    "MEDIO SAN JUAN": "CHOCÓ",
    "NOVITA": "CHOCÓ",
    "NUQUI": "CHOCÓ",
    "RIO IRO": "CHOCÓ",
    "RIO QUITO": "CHOCÓ",
    "SAN JOSE DEL PALMAR": "CHOCÓ",
    "SIPI": "CHOCÓ",
    "TADO": "CHOCÓ",
    "UNGUIA": "CHOCÓ",
    "UNION PANAMERICANA": "CHOCÓ",

    // ─── CÓRDOBA (30) ─────────────────────────────────────────────────────────
    "MONTERIA": "CÓRDOBA",
    "AYAPEL": "CÓRDOBA",
    "CANALETE": "CÓRDOBA",
    "CERETE": "CÓRDOBA",
    "CHIMA": "CÓRDOBA",
    "CHINU": "CÓRDOBA",
    "CIENAGA DE ORO": "CÓRDOBA",
    "COTORRA": "CÓRDOBA",
    "LA APARTADA": "CÓRDOBA",
    "LORICA": "CÓRDOBA",
    "LOS CORDOBAS": "CÓRDOBA",
    "MOMIL": "CÓRDOBA",
    "MONTELIBANO": "CÓRDOBA",
    "MONITOS": "CÓRDOBA",
    "PLANETA RICA": "CÓRDOBA",
    "PUEBLO NUEVO": "CÓRDOBA",
    "PUERTO ESCONDIDO": "CÓRDOBA",
    "PUERTO LIBERTADOR": "CÓRDOBA",
    "PURISIMA": "CÓRDOBA",
    "SAHAGUN": "CÓRDOBA",
    "SAN ANDRES DE SOTAVENTO": "CÓRDOBA",
    "SAN ANTERO": "CÓRDOBA",
    "SAN BERNARDO DEL VIENTO": "CÓRDOBA",
    "SAN JOSE DE URE": "CÓRDOBA",
    "SAN PELAYO": "CÓRDOBA",
    "TIERRALTA": "CÓRDOBA",
    "TUCHIN": "CÓRDOBA",
    "VALENCIA": "CÓRDOBA",

    // ─── CUNDINAMARCA (116 + Bogotá D.C.) ────────────────────────────────────
    "BOGOTA": "CUNDINAMARCA",
    "BOGOTA D.C.": "CUNDINAMARCA",
    "D.C.": "CUNDINAMARCA",
    "AGUA DE DIOS": "CUNDINAMARCA",
    "ALBAN": "CUNDINAMARCA",
    "ANAPOIMA": "CUNDINAMARCA",
    "ANOLAIMA": "CUNDINAMARCA",
    "APULO": "CUNDINAMARCA",
    "ARBELAEZ": "CUNDINAMARCA",
    "BELTRAN": "CUNDINAMARCA",
    "BITUIMA": "CUNDINAMARCA",
    "BOJACA": "CUNDINAMARCA",
    "CABRERA": "CUNDINAMARCA",
    "CACHIPAY": "CUNDINAMARCA",
    "CAJICA": "CUNDINAMARCA",
    "CAPARRAPI": "CUNDINAMARCA",
    "CAQUEZA": "CUNDINAMARCA",
    "CARMEN DE CARUPA": "CUNDINAMARCA",
    "CHAGUANI": "CUNDINAMARCA",
    "CHIA": "CUNDINAMARCA",
    "CHIPAQUE": "CUNDINAMARCA",
    "CHOACHI": "CUNDINAMARCA",
    "CHOCONTA": "CUNDINAMARCA",
    "COGUA": "CUNDINAMARCA",
    "COTA": "CUNDINAMARCA",
    "CUCUNUBA": "CUNDINAMARCA",
    "EL COLEGIO": "CUNDINAMARCA",
    "EL ROSAL": "CUNDINAMARCA",
    "FACATATIVA": "CUNDINAMARCA",
    "FOMEQUE": "CUNDINAMARCA",
    "FOSCA": "CUNDINAMARCA",
    "FUNZA": "CUNDINAMARCA",
    "FUQUENE": "CUNDINAMARCA",
    "FUSAGASUGA": "CUNDINAMARCA",
    "GACHALA": "CUNDINAMARCA",
    "GACHANCIPA": "CUNDINAMARCA",
    "GACHETA": "CUNDINAMARCA",
    "GAMA": "CUNDINAMARCA",
    "GIRARDOT": "CUNDINAMARCA",
    "GUACHETA": "CUNDINAMARCA",
    "GUADUAS": "CUNDINAMARCA",
    "GUASCA": "CUNDINAMARCA",
    "GUATAQUI": "CUNDINAMARCA",
    "GUATAVITA": "CUNDINAMARCA",
    "GUAYABAL DE SIQUIMA": "CUNDINAMARCA",
    "GUAYABETAL": "CUNDINAMARCA",
    "GUTIERREZ": "CUNDINAMARCA",
    "JERUSALEN": "CUNDINAMARCA",
    "JUNIN": "CUNDINAMARCA",
    "LA CALERA": "CUNDINAMARCA",
    "LA MESA": "CUNDINAMARCA",
    "LA PALMA": "CUNDINAMARCA",
    "LA PENA": "CUNDINAMARCA",
    "LENGUAZAQUE": "CUNDINAMARCA",
    "MACHETA": "CUNDINAMARCA",
    "MADRID": "CUNDINAMARCA",
    "MANTA": "CUNDINAMARCA",
    "MEDINA": "CUNDINAMARCA",
    "MOSQUERA": "CUNDINAMARCA",
    "NARINO": "CUNDINAMARCA",   // municipio Nariño, Cundinamarca
    "NEMACON": "CUNDINAMARCA",
    "NILO": "CUNDINAMARCA",
    "NIMAIMA": "CUNDINAMARCA",
    "NOCAIMA": "CUNDINAMARCA",
    "PACHO": "CUNDINAMARCA",
    "PAIME": "CUNDINAMARCA",
    "PANDI": "CUNDINAMARCA",
    "PARATEBUENO": "CUNDINAMARCA",
    "PASCA": "CUNDINAMARCA",
    "PUERTO SALGAR": "CUNDINAMARCA",
    "PULI": "CUNDINAMARCA",
    "QUEBRADANEGRA": "CUNDINAMARCA",
    "QUETAME": "CUNDINAMARCA",
    "QUIPILE": "CUNDINAMARCA",
    "SAN ANTONIO DEL TEQUENDAMA": "CUNDINAMARCA",
    "SAN BERNARDO": "CUNDINAMARCA",
    "SAN CAYETANO": "CUNDINAMARCA",
    "SAN JUAN DE RIO SECO": "CUNDINAMARCA",
    "SASAIMA": "CUNDINAMARCA",
    "SESQUILE": "CUNDINAMARCA",
    "SIBATE": "CUNDINAMARCA",
    "SILVANIA": "CUNDINAMARCA",
    "SIMIJACA": "CUNDINAMARCA",
    "SOACHA": "CUNDINAMARCA",
    "SOPO": "CUNDINAMARCA",
    "SUBACHOQUE": "CUNDINAMARCA",
    "SUESCA": "CUNDINAMARCA",
    "SUPATA": "CUNDINAMARCA",
    "SUSA": "CUNDINAMARCA",
    "SUTATAUSA": "CUNDINAMARCA",
    "TABIO": "CUNDINAMARCA",
    "TAUSA": "CUNDINAMARCA",
    "TENA": "CUNDINAMARCA",
    "TIBACUY": "CUNDINAMARCA",
    "TIBIRITA": "CUNDINAMARCA",
    "TOCAIMA": "CUNDINAMARCA",
    "TOCANCIPA": "CUNDINAMARCA",
    "TOPAIPI": "CUNDINAMARCA",
    "UBALA": "CUNDINAMARCA",
    "UBATE": "CUNDINAMARCA",
    "UNE": "CUNDINAMARCA",
    "UTICA": "CUNDINAMARCA",
    "VENECIA": "CUNDINAMARCA",
    "VERGARA": "CUNDINAMARCA",
    "VIANI": "CUNDINAMARCA",
    "VILLAGOMEZ": "CUNDINAMARCA",
    "VILLAPINZON": "CUNDINAMARCA",
    "VILLETA": "CUNDINAMARCA",
    "VIOTA": "CUNDINAMARCA",
    "YACOPI": "CUNDINAMARCA",
    "ZIPACON": "CUNDINAMARCA",
    "ZIPAQUIRA": "CUNDINAMARCA",

    // ─── GUAINÍA (8) ──────────────────────────────────────────────────────────
    "INIRIDA": "GUAINÍA",
    "BARRANCO MINAS": "GUAINÍA",
    "CACAHUAL": "GUAINÍA",
    "LA GUADALUPE": "GUAINÍA",
    "MAPIRIPANA": "GUAINÍA",
    "MORICHAL": "GUAINÍA",
    "PANA PANA": "GUAINÍA",
    "SAN FELIPE": "GUAINÍA",

    // ─── GUAVIARE (4) ─────────────────────────────────────────────────────────
    "SAN JOSE DEL GUAVIARE": "GUAVIARE",
    "EL RETORNO": "GUAVIARE",
    "CALAMAR DEL GUAVIARE": "GUAVIARE",  // forma larga para evitar conflicto con Calamar, Bolívar

    // ─── HUILA (37) ───────────────────────────────────────────────────────────
    "NEIVA": "HUILA",
    "ACEVEDO": "HUILA",
    "AGRADO": "HUILA",
    "AIPE": "HUILA",
    "ALGECIRAS": "HUILA",
    "ALTAMIRA": "HUILA",
    "BARAYA": "HUILA",
    "CAMPOALEGRE": "HUILA",
    "COLOMBIA": "HUILA",        // municipio Colombia, Huila
    "ELIAS": "HUILA",
    "GARZON": "HUILA",
    "GIGANTE": "HUILA",
    "GUADALUPE": "HUILA",
    "HOBO": "HUILA",
    "IQUIRA": "HUILA",
    "ISNOS": "HUILA",
    "LA ARGENTINA": "HUILA",
    "LA PLATA": "HUILA",
    "NATAGA": "HUILA",
    "OPORAPA": "HUILA",
    "PAICOL": "HUILA",
    "PALERMO": "HUILA",
    "PITAL": "HUILA",
    "PITALITO": "HUILA",
    "RIVERA": "HUILA",
    "SALADOBLANCO": "HUILA",
    "SAN AGUSTIN": "HUILA",
    "SUAZA": "HUILA",
    "TARQUI": "HUILA",
    "TESALIA": "HUILA",
    "TELLO": "HUILA",
    "TERUEL": "HUILA",
    "TIMANA": "HUILA",
    "VILLAVIEJA": "HUILA",
    "YAGUARA": "HUILA",

    // ─── LA GUAJIRA (15) ──────────────────────────────────────────────────────
    "RIOHACHA": "LA GUAJIRA",
    "BARRANCAS": "LA GUAJIRA",
    "DIBULLA": "LA GUAJIRA",
    "DISTRACCION": "LA GUAJIRA",
    "EL MOLINO": "LA GUAJIRA",
    "FONSECA": "LA GUAJIRA",
    "HATONUEVO": "LA GUAJIRA",
    "MAICAO": "LA GUAJIRA",
    "MANAURE": "LA GUAJIRA",
    "SAN JUAN DEL CESAR": "LA GUAJIRA",
    "URIBIA": "LA GUAJIRA",
    "URUMITA": "LA GUAJIRA",

    // ─── MAGDALENA (30) ───────────────────────────────────────────────────────
    "SANTA MARTA": "MAGDALENA",
    "ALGARROBO": "MAGDALENA",
    "ARACATACA": "MAGDALENA",
    "ARIGUANI": "MAGDALENA",
    "CERRO DE SAN ANTONIO": "MAGDALENA",
    "CHIVOLO": "MAGDALENA",
    "CIENAGA": "MAGDALENA",
    "EL BANCO": "MAGDALENA",
    "EL PINON": "MAGDALENA",
    "EL RETEN": "MAGDALENA",
    "FUNDACION": "MAGDALENA",
    "GUAMAL": "MAGDALENA",
    "NUEVA GRANADA": "MAGDALENA",
    "PEDRAZA": "MAGDALENA",
    "PIJINO DEL CARMEN": "MAGDALENA",
    "PIVIJAY": "MAGDALENA",
    "PLATO": "MAGDALENA",
    "PUEBLOVIEJO": "MAGDALENA",
    "REMOLINO": "MAGDALENA",
    "SABANAS DE SAN ANGEL": "MAGDALENA",
    "SAN SEBASTIAN DE BUENAVISTA": "MAGDALENA",
    "SAN ZENON": "MAGDALENA",
    "SANTA ANA": "MAGDALENA",
    "SANTA BARBARA DE PINTO": "MAGDALENA",
    "SITIONUEVO": "MAGDALENA",
    "TENERIFE": "MAGDALENA",
    "ZAPAYAN": "MAGDALENA",
    "ZONA BANANERA": "MAGDALENA",

    // ─── META (29) ────────────────────────────────────────────────────────────
    "VILLAVICENCIO": "META",
    "ACACIAS": "META",
    "BARRANCA DE UPIA": "META",
    "CABUYARO": "META",
    "CASTILLA LA NUEVA": "META",
    "CUBARRAL": "META",
    "CUMARAL": "META",
    "EL CALVARIO": "META",
    "EL CASTILLO": "META",
    "EL DORADO": "META",
    "FUENTE DE ORO": "META",
    "GRANADA": "META",
    "LA MACARENA": "META",
    "LEJANIAS": "META",
    "MAPIRIPAN": "META",
    "MESETAS": "META",
    "PUERTO CONCORDIA": "META",
    "PUERTO GAITAN": "META",
    "PUERTO LLERAS": "META",
    "PUERTO LOPEZ": "META",
    "RESTREPO": "META",
    "SAN CARLOS DE GUAROA": "META",
    "SAN JUAN DE ARAMA": "META",
    "SAN JUANITO": "META",
    "SAN MARTIN": "META",
    "VISTA HERMOSA": "META",

    // ─── NARIÑO (64) ──────────────────────────────────────────────────────────
    "PASTO": "NARIÑO",
    "ALDANA": "NARIÑO",
    "ANCUYA": "NARIÑO",
    "BARBACOAS": "NARIÑO",
    "BUESACO": "NARIÑO",
    "CHACHAGUI": "NARIÑO",
    "COLON": "NARIÑO",
    "CONSACA": "NARIÑO",
    "CONTADERO": "NARIÑO",
    "CUASPUD": "NARIÑO",
    "CUMBAL": "NARIÑO",
    "CUMBITARA": "NARIÑO",
    "EL CHARCO": "NARIÑO",
    "EL ROSARIO": "NARIÑO",
    "EL TABLON DE GOMEZ": "NARIÑO",
    "FRANCISCO PIZARRO": "NARIÑO",
    "FUNES": "NARIÑO",
    "GUACHUCAL": "NARIÑO",
    "GUAITARILLA": "NARIÑO",
    "GUALMATAN": "NARIÑO",
    "ILES": "NARIÑO",
    "IMUES": "NARIÑO",
    "IPIALES": "NARIÑO",
    "LA CRUZ": "NARIÑO",
    "LA FLORIDA": "NARIÑO",
    "LA LLANADA": "NARIÑO",
    "LA TOLA": "NARIÑO",
    "LEIVA": "NARIÑO",
    "LINARES": "NARIÑO",
    "LOS ANDES": "NARIÑO",
    "MAGUI PAYAN": "NARIÑO",
    "MALLAMA": "NARIÑO",
    "OLAYA HERRERA": "NARIÑO",
    "OSPINA": "NARIÑO",
    "POLICARPA": "NARIÑO",
    "POTOSI": "NARIÑO",
    "PROVIDENCIA": "NARIÑO",
    "PUERRES": "NARIÑO",
    "PUPIALES": "NARIÑO",
    "RICAURTE": "NARIÑO",
    "ROBERTO PAYAN": "NARIÑO",
    "SAMANIEGO": "NARIÑO",
    "SAN LORENZO": "NARIÑO",
    "SAN PABLO NARINO": "NARIÑO",      // municipio San Pablo, Nariño (SAN PABLO como clave ya pertenece a Bolívar)
    "SAN PEDRO DE CARTAGO": "NARIÑO",
    "SANDONA": "NARIÑO",
    "SANTACRUZ": "NARIÑO",
    "SAPUYES": "NARIÑO",
    "TAMINANGO": "NARIÑO",
    "TANGUA": "NARIÑO",
    "TUMACO": "NARIÑO",
    "TUQUERRES": "NARIÑO",
    "YACUANQUER": "NARIÑO",

    // ─── NORTE DE SANTANDER (40) ──────────────────────────────────────────────
    "CUCUTA": "NORTE DE SANTANDER",
    "ABREGO": "NORTE DE SANTANDER",
    "ARBOLEDAS": "NORTE DE SANTANDER",
    "BOCHALEMA": "NORTE DE SANTANDER",
    "BUCARASICA": "NORTE DE SANTANDER",
    "CACHIRA": "NORTE DE SANTANDER",
    "CALIFORNIA": "NORTE DE SANTANDER",
    "CHINACOTA": "NORTE DE SANTANDER",
    "CHITAGA": "NORTE DE SANTANDER",
    "CONVENCION": "NORTE DE SANTANDER",
    "CUCUTILLA": "NORTE DE SANTANDER",
    "DURANIA": "NORTE DE SANTANDER",
    "EL CARMEN": "NORTE DE SANTANDER",
    "EL TARRA": "NORTE DE SANTANDER",
    "EL ZULIA": "NORTE DE SANTANDER",
    "GRAMALOTE": "NORTE DE SANTANDER",
    "HACARI": "NORTE DE SANTANDER",
    "HERRAN": "NORTE DE SANTANDER",
    "LA ESPERANZA": "NORTE DE SANTANDER",
    "LA PLAYA": "NORTE DE SANTANDER",
    "LABATECA": "NORTE DE SANTANDER",
    "LOS PATIOS": "NORTE DE SANTANDER",
    "LOURDES": "NORTE DE SANTANDER",
    "MUTISCUA": "NORTE DE SANTANDER",
    "OCANA": "NORTE DE SANTANDER",
    "PAMPLONA": "NORTE DE SANTANDER",
    "PAMPLONITA": "NORTE DE SANTANDER",
    "RAGONVALIA": "NORTE DE SANTANDER",
    "SALAZAR": "NORTE DE SANTANDER",
    "SAN CALIXTO": "NORTE DE SANTANDER",
    "SARDINATA": "NORTE DE SANTANDER",
    "SILOS": "NORTE DE SANTANDER",
    "TEORAMA": "NORTE DE SANTANDER",
    "TIBU": "NORTE DE SANTANDER",
    "TOLEDO": "NORTE DE SANTANDER",
    "VILLA CARO": "NORTE DE SANTANDER",
    "VILLA DEL ROSARIO": "NORTE DE SANTANDER",

    // ─── PUTUMAYO (13) ────────────────────────────────────────────────────────
    "MOCOA": "PUTUMAYO",
    "ORITO": "PUTUMAYO",
    "PUERTO ASIS": "PUTUMAYO",
    "PUERTO CAICEDO": "PUTUMAYO",
    "PUERTO GUZMAN": "PUTUMAYO",
    "PUERTO LEGUIZAMO": "PUTUMAYO",
    "SAN MIGUEL": "PUTUMAYO",
    "SIBUNDOY": "PUTUMAYO",
    "VALLE DEL GUAMUEZ": "PUTUMAYO",
    "VILLAGARZON": "PUTUMAYO",

    // ─── QUINDÍO (12) ─────────────────────────────────────────────────────────
    "ARMENIA": "QUINDÍO",       // capital departamental (más conocida)
    "CALARCA": "QUINDÍO",
    "CIRCASIA": "QUINDÍO",
    "FILANDIA": "QUINDÍO",
    "GENOVA": "QUINDÍO",
    "LA TEBAIDA": "QUINDÍO",
    "MONTENEGRO": "QUINDÍO",
    "PIJAO": "QUINDÍO",
    "QUIMBAYA": "QUINDÍO",
    "SALENTO": "QUINDÍO",

    // ─── RISARALDA (14) ───────────────────────────────────────────────────────
    "PEREIRA": "RISARALDA",
    "APIA": "RISARALDA",
    "BELEN DE UMBRIA": "RISARALDA",
    "DOSQUEBRADAS": "RISARALDA",
    "GUATICA": "RISARALDA",
    "LA CELIA": "RISARALDA",
    "LA VIRGINIA": "RISARALDA",
    "MARSELLA": "RISARALDA",
    "MISTRATO": "RISARALDA",
    "PUEBLO RICO": "RISARALDA",
    "QUINCHIA": "RISARALDA",
    "SANTA ROSA DE CABAL": "RISARALDA",
    "SANTUARIO": "RISARALDA",

    // ─── SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA (2) ────────────────────────
    "SAN ANDRES": "SAN ANDRÉS",
    "SAN ANDRES ISLA": "SAN ANDRÉS",
    "PROVIDENCIA ISLA": "SAN ANDRÉS",

    // ─── SANTANDER (87) ───────────────────────────────────────────────────────
    "BUCARAMANGA": "SANTANDER",
    "AGUADA": "SANTANDER",
    "ARATOCA": "SANTANDER",
    "BARICHARA": "SANTANDER",
    "BARRANCABERMEJA": "SANTANDER",
    "BOLIVAR": "SANTANDER",
    "CARCASI": "SANTANDER",
    "CEPITA": "SANTANDER",
    "CERRITO": "SANTANDER",
    "CHARALA": "SANTANDER",
    "CHARTA": "SANTANDER",
    "CHIPATA": "SANTANDER",
    "CIMITARRA": "SANTANDER",
    "CONCEPCION": "SANTANDER",
    "CONFINES": "SANTANDER",
    "CONTRATACION": "SANTANDER",
    "COROMORO": "SANTANDER",
    "CURITI": "SANTANDER",
    "EL CARMEN DE CHUCURI": "SANTANDER",
    "EL GUACAMAYO": "SANTANDER",
    "EL PLAYON": "SANTANDER",
    "ENCINO": "SANTANDER",
    "ENCISO": "SANTANDER",
    "FLORIAN": "SANTANDER",
    "FLORIDABLANCA": "SANTANDER",
    "GALAN": "SANTANDER",
    "GAMBITA": "SANTANDER",
    "GIRON": "SANTANDER",
    "GUACA": "SANTANDER",
    "GUAPOTA": "SANTANDER",
    "GUAVATA": "SANTANDER",
    "GUEPSA": "SANTANDER",
    "HATO": "SANTANDER",
    "JESUS MARIA": "SANTANDER",
    "JORDAN": "SANTANDER",
    "LA BELLEZA": "SANTANDER",
    "LANDAZURI": "SANTANDER",
    "LEBRIJA": "SANTANDER",
    "LOS SANTOS": "SANTANDER",
    "MACARAVITA": "SANTANDER",
    "MALAGA": "SANTANDER",
    "MATANZA": "SANTANDER",
    "MOGOTES": "SANTANDER",
    "MOLAGAVITA": "SANTANDER",
    "OCAMONTE": "SANTANDER",
    "OIBA": "SANTANDER",
    "ONZAGA": "SANTANDER",
    "PALMAR": "SANTANDER",
    "PALMAS DEL SOCORRO": "SANTANDER",
    "PARAMO": "SANTANDER",
    "PIEDECUESTA": "SANTANDER",
    "PINCHOTE": "SANTANDER",
    "PUENTE NACIONAL": "SANTANDER",
    "PUERTO PARRA": "SANTANDER",
    "PUERTO WILCHES": "SANTANDER",
    "SABANA DE TORRES": "SANTANDER",
    "SAN BENITO": "SANTANDER",
    "SAN GIL": "SANTANDER",
    "SAN JOAQUIN": "SANTANDER",
    "SAN JOSE DE MIRANDA": "SANTANDER",
    "SAN VICENTE DE CHUCURI": "SANTANDER",
    "SANTA HELENA DEL OPON": "SANTANDER",
    "SIMACOTA": "SANTANDER",
    "SOCORRO": "SANTANDER",
    "SUAITA": "SANTANDER",
    "SUCRE": "SANTANDER",
    "SURATA": "SANTANDER",
    "TONA": "SANTANDER",
    "VALLE DE SAN JOSE": "SANTANDER",
    "VELEZ": "SANTANDER",
    "VETAS": "SANTANDER",
    "ZAPATOCA": "SANTANDER",

    // ─── SUCRE (26) ───────────────────────────────────────────────────────────
    "SINCELEJO": "SUCRE",
    "CAIMITO": "SUCRE",
    "CHALAN": "SUCRE",
    "COLOSO": "SUCRE",
    "COROZAL": "SUCRE",
    "COVENAS": "SUCRE",
    "EL ROBLE": "SUCRE",
    "GALERAS": "SUCRE",
    "GUARANDA": "SUCRE",
    "LOS PALMITOS": "SUCRE",
    "MAJAGUAL": "SUCRE",
    "MORROA": "SUCRE",
    "OVEJAS": "SUCRE",
    "PALMITO": "SUCRE",
    "SAMPUES": "SUCRE",
    "SAN BENITO ABAD": "SUCRE",
    "SAN JUAN DE BETULIA": "SUCRE",
    "SAN LUIS DE SINCE": "SUCRE",
    "SAN MARCOS": "SUCRE",
    "SAN ONOFRE": "SUCRE",
    "SANTIAGO DE TOLU": "SUCRE",
    "SINCE": "SUCRE",
    "TOLUVIEJO": "SUCRE",

    // ─── TOLIMA (47) ──────────────────────────────────────────────────────────
    "IBAGUE": "TOLIMA",
    "ALPUJARRA": "TOLIMA",
    "ALVARADO": "TOLIMA",
    "AMBALEMA": "TOLIMA",
    "ANZOATEGUI": "TOLIMA",
    "ATACO": "TOLIMA",
    "CAJAMARCA": "TOLIMA",
    "CARMEN DE APICALA": "TOLIMA",
    "CASABIANCA": "TOLIMA",
    "CHAPARRAL": "TOLIMA",
    "COELLO": "TOLIMA",
    "COYAIMA": "TOLIMA",
    "CUNDAY": "TOLIMA",
    "DOLORES": "TOLIMA",
    "ESPINAL": "TOLIMA",
    "FALAN": "TOLIMA",
    "FLANDES": "TOLIMA",
    "FRESNO": "TOLIMA",
    "HERVEO": "TOLIMA",
    "HONDA": "TOLIMA",
    "ICONONZO": "TOLIMA",
    "LERIDA": "TOLIMA",
    "LIBANO": "TOLIMA",
    "MARIQUITA": "TOLIMA",
    "MELGAR": "TOLIMA",
    "MURILLO": "TOLIMA",
    "NATAGAIMA": "TOLIMA",
    "ORTEGA": "TOLIMA",
    "PALOCABILDO": "TOLIMA",
    "PIEDRAS": "TOLIMA",
    "PLANADAS": "TOLIMA",
    "PRADO": "TOLIMA",
    "PURIFICACION": "TOLIMA",
    "RIOBLANCO": "TOLIMA",
    "RONCESVALLES": "TOLIMA",
    "ROVIRA": "TOLIMA",
    "SALDANA": "TOLIMA",
    "SANTA ISABEL": "TOLIMA",
    "VALLE DE SAN JUAN": "TOLIMA",
    "VENADILLO": "TOLIMA",
    "VILLAHERMOSA": "TOLIMA",
    "VILLARRICA": "TOLIMA",

    // ─── VALLE DEL CAUCA (42) ─────────────────────────────────────────────────
    "CALI": "VALLE DEL CAUCA",
    "ALCALA": "VALLE DEL CAUCA",
    "ANDALUCIA": "VALLE DEL CAUCA",
    "ANSERMANUEVO": "VALLE DEL CAUCA",
    "BUENAVENTURA": "VALLE DEL CAUCA",
    "BUGA": "VALLE DEL CAUCA",
    "GUADALAJARA DE BUGA": "VALLE DEL CAUCA",
    "BUGALAGRANDE": "VALLE DEL CAUCA",
    "CAICEDONIA": "VALLE DEL CAUCA",
    "CALIMA": "VALLE DEL CAUCA",
    "CARTAGO": "VALLE DEL CAUCA",
    "DAGUA": "VALLE DEL CAUCA",
    "EL AGUILA": "VALLE DEL CAUCA",
    "EL CAIRO": "VALLE DEL CAUCA",
    "EL CERRITO": "VALLE DEL CAUCA",
    "EL DOVIO": "VALLE DEL CAUCA",
    "FLORIDA": "VALLE DEL CAUCA",
    "GINEBRA": "VALLE DEL CAUCA",
    "GUACARI": "VALLE DEL CAUCA",
    "JAMUNDI": "VALLE DEL CAUCA",
    "LA CUMBRE": "VALLE DEL CAUCA",
    "LA UNION": "VALLE DEL CAUCA",
    "LA VICTORIA": "VALLE DEL CAUCA",
    "OBANDO": "VALLE DEL CAUCA",
    "PALMIRA": "VALLE DEL CAUCA",
    "PRADERA": "VALLE DEL CAUCA",
    "RIOFRIO": "VALLE DEL CAUCA",
    "ROLDANILLO": "VALLE DEL CAUCA",
    "SEVILLA": "VALLE DEL CAUCA",
    "TORO": "VALLE DEL CAUCA",
    "TRUJILLO": "VALLE DEL CAUCA",
    "TULUA": "VALLE DEL CAUCA",
    "ULLOA": "VALLE DEL CAUCA",
    "VERSALLES": "VALLE DEL CAUCA",
    "VIJES": "VALLE DEL CAUCA",
    "YOTOCO": "VALLE DEL CAUCA",
    "YUMBO": "VALLE DEL CAUCA",
    "ZARZAL": "VALLE DEL CAUCA",

    // ─── VAUPÉS (4) ───────────────────────────────────────────────────────────
    "MITU": "VAUPÉS",
    "CARURU": "VAUPÉS",
    "TARAIRA": "VAUPÉS",
    "YAVARATE": "VAUPÉS",

    // ─── VICHADA (4) ──────────────────────────────────────────────────────────
    "PUERTO CARRENO": "VICHADA",
    "CUMARIBO": "VICHADA",
    "LA PRIMAVERA": "VICHADA",
    "SANTA ROSALIA": "VICHADA",

};

/**
 * Devuelve el nombre del departamento colombiano a partir del nombre del municipio.
 *
 * Normaliza el input automáticamente (mayúsculas, sin tildes) antes de buscar,
 * por lo que "Armenia", "ARMENIA" y "armenia" producen el mismo resultado.
 *
 * @param municipio - Nombre del municipio (libre, con o sin tildes)
 * @returns Nombre del departamento (con tildes, para visualización) o "N/A" si no se encuentra
 *
 * @example
 * obtenerDepartamento("Armenia")   // → "QUINDÍO"
 * obtenerDepartamento("bogotá")    // → "CUNDINAMARCA"
 * obtenerDepartamento("Medellín")  // → "ANTIOQUIA"
 * obtenerDepartamento("XYZ")       // → "N/A"
 */
export function obtenerDepartamento(municipio: string): string {
    if (!municipio || municipio.trim() === "") return "N/A";
    const clave = normalizarTexto(municipio);
    return MUNICIPIOS_COLOMBIA[clave] ?? "N/A";
}
